#!/usr/bin/env python3
"""
build.py — Website Builder System v2
Template engine + plugin architecture + export modes + watch mode.

Usage:
  python build.py                                    # static, config.json → ../dist
  python build.py --config my.json                   # custom config
  python build.py --out ./out                        # custom output dir
  python build.py --mode flask                       # Flask export
  python build.py --mode react                       # React export
  python build.py --minify                           # minify HTML output
  python build.py --watch                            # auto-rebuild on file change
  python build.py --preview                          # build + serve localhost:8080
  python build.py --mode flask --preview --port 3000
"""

import json, os, re, sys, shutil, argparse, time, threading, http.server, colorsys
from pathlib import Path

HERE           = Path(__file__).parent
DEFAULT_CONFIG = HERE / "config.json"
DEFAULT_OUT    = HERE.parent / "dist"

# Add builder dir to path so engine/plugins/exporter can be imported
sys.path.insert(0, str(HERE))

from engine import render_file, build_context, render


# ═══════════════════════════════════════════════════════════════════════════════
# 1. THEME ENGINE
# ═══════════════════════════════════════════════════════════════════════════════

def _hex_to_rgb(h: str) -> tuple:
    h = h.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)

def _shade(hex_color: str, factor: float) -> str:
    r, g, b = _hex_to_rgb(hex_color)
    return "#{:02x}{:02x}{:02x}".format(
        min(255, max(0, int(r * factor))),
        min(255, max(0, int(g * factor))),
        min(255, max(0, int(b * factor))),
    )

def generate_css(cfg: dict) -> str:
    p  = cfg["primary_color"]
    s  = cfg["secondary_color"]
    pr, pg, pb = _hex_to_rgb(p)
    sr, sg, sb = _hex_to_rgb(s)
    font       = cfg.get("font", "Inter")
    font_url   = font.replace(" ", "+")
    f          = cfg.get("features", {})

    anim_css = """
.reveal,.reveal-left,.reveal-right{opacity:0;transition:opacity .65s ease,transform .65s ease}
.reveal{transform:translateY(22px)}.reveal-left{transform:translateX(-22px)}.reveal-right{transform:translateX(22px)}
.reveal.visible,.reveal-left.visible,.reveal-right.visible{opacity:1;transform:none}
@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-8px)}}
.float-1{animation:float 3s ease-in-out infinite}.float-2{animation:float 3s ease-in-out infinite .9s}
body{animation:pageFadeIn .3s ease}
@keyframes pageFadeIn{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}
""" if f.get("animations") else ""

    sp_css = "#scrollProgress{position:fixed;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,var(--primary),var(--secondary));z-index:9999;transform-origin:left;transform:scaleX(0);transition:transform .1s linear}\n" if f.get("scroll_progress") else ""
    btt_css = "#backToTop{opacity:0;pointer-events:none;transition:opacity .3s}#backToTop.visible{opacity:1;pointer-events:auto}\n" if f.get("back_to_top") else ""
    dark_css = ".dark{--bg:#030712;--surface:#111827;--text:#f9fafb;--text-muted:#9ca3af;--border:#1f2937}\n" if f.get("dark_mode") else ""

    return f"""/* Generated by Website Builder System — {cfg['site_name']} */
@import url('https://fonts.googleapis.com/css2?family={font_url}:wght@300;400;500;600;700;800&display=swap');
:root{{
  --primary:{p};--secondary:{s};
  --primary-rgb:{pr},{pg},{pb};--secondary-rgb:{sr},{sg},{sb};
  --primary-light:{_shade(p,1.3)};--primary-dark:{_shade(p,0.75)};
  --bg:#ffffff;--surface:#f9fafb;--text:#111827;--text-muted:#6b7280;--border:#e5e7eb;--radius:1rem;
}}
{dark_css}*,*::before,*::after{{box-sizing:border-box;margin:0;padding:0}}
html{{scroll-behavior:smooth}}
body{{font-family:'{font}','Segoe UI',system-ui,sans-serif;background:var(--bg);color:var(--text);line-height:1.7;-webkit-font-smoothing:antialiased}}
a{{text-decoration:none;color:inherit}}img{{max-width:100%;display:block}}
.gradient-text{{background:linear-gradient(135deg,var(--primary),var(--secondary));-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}}
.btn-gradient{{background:linear-gradient(135deg,var(--primary),var(--secondary));color:#fff;transition:transform .2s,box-shadow .2s,opacity .15s}}
.btn-gradient:hover{{transform:translateY(-2px) scale(1.02);box-shadow:0 8px 28px rgba(var(--primary-rgb),.4);opacity:.93}}
.btn-gradient:active{{transform:scale(.98)}}
.btn-outline-primary{{border:2px solid var(--primary);color:var(--primary);transition:background .2s,color .2s,transform .2s,box-shadow .2s}}
.btn-outline-primary:hover{{background:var(--primary);color:#fff;transform:translateY(-2px);box-shadow:0 6px 20px rgba(var(--primary-rgb),.3)}}
.nav-link{{position:relative}}.nav-link::after{{content:'';position:absolute;bottom:-2px;left:50%;width:0;height:2px;background:var(--primary);transition:width .2s,left .2s}}
.nav-link:hover::after,.nav-link.active::after{{width:100%;left:0}}.nav-link.active{{color:var(--primary)!important}}
.card-hover{{transition:transform .22s ease,box-shadow .22s ease}}.card-hover:hover{{transform:translateY(-5px);box-shadow:0 16px 40px rgba(0,0,0,.1)}}
.card-gradient-border{{position:relative;background:var(--bg);border-radius:var(--radius)}}
.card-gradient-border::before{{content:'';position:absolute;inset:0;border-radius:var(--radius);padding:1.5px;background:linear-gradient(135deg,var(--primary),var(--secondary));-webkit-mask:linear-gradient(#fff 0 0) content-box,linear-gradient(#fff 0 0);-webkit-mask-composite:xor;mask-composite:exclude;opacity:0;transition:opacity .2s}}
.card-gradient-border:hover::before{{opacity:1}}
.glass{{background:rgba(255,255,255,.7);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);border:1px solid rgba(255,255,255,.3)}}
.dark .glass{{background:rgba(17,24,39,.7);border-color:rgba(255,255,255,.08)}}
.shadow-glow{{box-shadow:0 0 24px rgba(var(--primary-rgb),.35)!important}}
.text-primary{{color:var(--primary)!important}}.bg-primary{{background-color:var(--primary)!important}}
.bg-primary-10{{background-color:rgba(var(--primary-rgb),.1)!important}}.bg-primary-15{{background-color:rgba(var(--primary-rgb),.15)!important}}
.border-primary{{border-color:var(--primary)!important}}
.toast-enter{{animation:toastIn .35s ease forwards}}.toast-leave{{animation:toastOut .3s ease forwards}}
@keyframes toastIn{{from{{opacity:0;transform:translateY(10px) scale(.95)}}to{{opacity:1;transform:none}}}}
@keyframes toastOut{{from{{opacity:1;transform:none}}to{{opacity:0;transform:translateY(10px) scale(.95)}}}}
.scrollbar-hide{{-ms-overflow-style:none;scrollbar-width:none}}.scrollbar-hide::-webkit-scrollbar{{display:none}}
:focus-visible{{outline:2px solid var(--primary);outline-offset:3px;border-radius:6px}}
[x-cloak]{{display:none!important}}
{anim_css}{sp_css}{btt_css}"""


# ═══════════════════════════════════════════════════════════════════════════════
# 2. SCRIPT.JS GENERATOR
# ═══════════════════════════════════════════════════════════════════════════════

def generate_js(cfg: dict) -> str:
    f = cfg.get("features", {})
    dark    = f.get("dark_mode")
    anim    = f.get("animations")
    counter = f.get("counter_animation")
    sp      = f.get("scroll_progress")
    btt     = f.get("back_to_top")

    dark_js = """
function applyDark(d){document.documentElement.classList.toggle('dark',d);const s=document.getElementById('iconSun'),m=document.getElementById('iconMoon');if(s)s.classList.toggle('hidden',!d);if(m)m.classList.toggle('hidden',d);}
function toggleDark(){const d=!document.documentElement.classList.contains('dark');localStorage.setItem('dark',d);applyDark(d);}
applyDark(localStorage.getItem('dark')==='true');
""" if dark else ""

    anim_js = """
const _ro=new IntersectionObserver(e=>{e.forEach(x=>{if(x.isIntersecting){x.target.classList.add('visible');_ro.unobserve(x.target);}});},{threshold:.1,rootMargin:'0px 0px -40px 0px'});
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.reveal,.reveal-left,.reveal-right').forEach(el=>_ro.observe(el));});
""" if anim else ""

    counter_js = """
function _animCounter(el){const t=parseInt(el.dataset.target),s=el.dataset.suffix||'';let c=0;const step=Math.ceil(t/60);const ti=setInterval(()=>{c=Math.min(c+step,t);el.textContent=c.toLocaleString()+s;if(c>=t)clearInterval(ti);},22);}
const _co=new IntersectionObserver(e=>{e.forEach(x=>{if(x.isIntersecting){x.target.querySelectorAll('[data-target]').forEach(_animCounter);_co.unobserve(x.target);}});},{threshold:.4});
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.stats-row').forEach(el=>_co.observe(el));});
""" if counter else ""

    scroll_js = ""
    if sp or btt:
        sp_line  = "const _pb=document.getElementById('scrollProgress');if(_pb)_pb.style.transform=`scaleX(${scrollY/(document.documentElement.scrollHeight-innerHeight)||0})`;" if sp else ""
        btt_line = "const _bt=document.getElementById('backToTop');if(_bt)_bt.classList.toggle('visible',scrollY>400);" if btt else ""
        scroll_js = f"window.addEventListener('scroll',()=>{{{sp_line}{btt_line}const n=document.getElementById('mainNav');if(n)n.style.boxShadow=scrollY>8?'0 4px 24px rgba(0,0,0,.12)':'none';}},{{passive:true}});\n"

    return f"""'use strict';
// Generated by Website Builder System — {cfg['site_name']}
{dark_js}{anim_js}{counter_js}{scroll_js}
(function(){{const p=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav-link').forEach(a=>{{const h=(a.getAttribute('href')||'').split('/').pop();if(h===p||(p===''&&h==='index.html'))a.classList.add('active');}});}})();
window.showToast=function(msg,type='success'){{const c={{success:'bg-emerald-500',error:'bg-red-500',info:'bg-blue-500',warning:'bg-amber-500'}};const t=document.createElement('div');t.className=`fixed bottom-6 right-6 z-[9999] px-5 py-3 rounded-2xl text-white text-sm font-semibold shadow-2xl toast-enter flex items-center gap-2 ${{c[type]||c.success}}`;t.innerHTML=`<span>${{msg}}</span><button onclick="this.parentElement.remove()" class="ml-2 opacity-70 hover:opacity-100 text-lg leading-none" aria-label="Close">×</button>`;document.body.appendChild(t);setTimeout(()=>{{t.classList.add('toast-leave');setTimeout(()=>t.remove(),300);}},3500);}};
document.addEventListener('DOMContentLoaded',()=>{{const cf=document.getElementById('contactForm');if(cf)cf.addEventListener('submit',e=>{{e.preventDefault();const b=cf.querySelector('[type=submit]'),o=b.textContent;b.textContent='Sending…';b.disabled=true;setTimeout(()=>{{cf.reset();b.textContent=o;b.disabled=false;showToast("Message sent! We'll get back to you soon. ✅");}},1200);}});}});
document.addEventListener('click',e=>{{const a=e.target.closest('a[href^="#"]');if(!a)return;const t=document.querySelector(a.getAttribute('href'));if(t){{e.preventDefault();t.scrollIntoView({{behavior:'smooth',block:'start'}});}}}});
"""


# ═══════════════════════════════════════════════════════════════════════════════
# 3. CONTEXT ENRICHMENT (section-specific extra vars)
# ═══════════════════════════════════════════════════════════════════════════════

def _enrich_context(ctx: dict, cfg: dict) -> dict:
    """Add computed/derived values that templates need."""
    f    = cfg.get("features", {})
    anim = f.get("animations", True)

    ctx["reveal_class"]       = "reveal"       if anim else ""
    ctx["reveal_left_class"]  = "reveal-left"  if anim else ""
    ctx["reveal_right_class"] = "reveal-right" if anim else ""

    # Hero line split
    tagline = cfg.get("tagline", "Build the Future Faster Than Ever")
    words   = tagline.split()
    mid     = len(words) // 2
    ctx["hero_line1"] = " ".join(words[:mid])
    ctx["hero_line2"] = " ".join(words[mid:])

    # Portfolio filter
    items = cfg.get("content", {}).get("portfolio_items", [])
    if f.get("portfolio_filter") and items:
        cats = sorted(set(i["category"] for i in items))
        btns = '<button @click="filter=\'all\'" :class="filter===\'all\'?\'btn-gradient\':\'btn-outline-primary\'" class="px-5 py-2 rounded-full text-sm font-semibold transition-all focus:outline-none focus:ring-2 focus:ring-[var(--primary)]" :aria-pressed="(filter===\'all\').toString()">All</button>\n      '
        for cat in cats:
            btns += f'<button @click="filter=\'{cat}\'" :class="filter===\'{cat}\'?\'btn-gradient\':\'btn-outline-primary\'" class="px-5 py-2 rounded-full text-sm font-semibold transition-all focus:outline-none focus:ring-2 focus:ring-[var(--primary)]" :aria-pressed="(filter===\'{cat}\').toString()">{cat.title()}</button>\n      '
        ctx["portfolio_x_data"]        = 'x-data="{filter:\'all\'}"'
        ctx["portfolio_filter_buttons"] = f'<div class="flex flex-wrap gap-3 justify-center mb-14 {ctx["reveal_class"]}" role="group" aria-label="Filter projects">{btns}</div>'
        for item in items:
            item["portfolio_item_show"] = f"x-show=\"filter==='all'||filter==='{item['category']}'\""
    else:
        ctx["portfolio_x_data"]        = ""
        ctx["portfolio_filter_buttons"] = ""
        for item in items:
            item["portfolio_item_show"] = ""

    # Pricing
    pricing_toggle = f.get("pricing_toggle", True)
    ctx["pricing_x_data"]    = 'x-data="{yearly:false}"' if pricing_toggle else ""
    ctx["pricing_toggle_html"] = """<div class="inline-flex items-center gap-1 bg-gray-100 dark:bg-gray-800 rounded-full p-1 mt-6" role="group" aria-label="Billing period">
      <button @click="yearly=false" :class="!yearly?'btn-gradient':'text-gray-500 dark:text-gray-400'" class="px-5 py-2 rounded-full text-sm font-semibold transition-all focus:outline-none focus:ring-2 focus:ring-[var(--primary)]" :aria-pressed="(!yearly).toString()">Monthly</button>
      <button @click="yearly=true"  :class="yearly?'btn-gradient':'text-gray-500 dark:text-gray-400'" class="px-5 py-2 rounded-full text-sm font-semibold transition-all focus:outline-none focus:ring-2 focus:ring-[var(--primary)]" :aria-pressed="yearly.toString()">Yearly <span class="text-xs font-bold text-emerald-500 ml-1">-20%</span></button>
    </div>""" if pricing_toggle else ""

    # Enrich each pricing tier
    for tier in cfg.get("content", {}).get("pricing", []):
        pm = tier.get("price_monthly", 0)
        py = tier.get("price_yearly",  0)
        featured = tier.get("featured", False)
        tier["pricing_card_class"] = "border-2 border-[var(--primary)] shadow-glow" if featured else "border border-gray-200 dark:border-gray-700"
        tier["pricing_tier_class"] = "text-primary" if featured else "text-gray-500 dark:text-gray-400"
        tier["pricing_badge"]      = '<div class="absolute -top-3.5 left-1/2 -translate-x-1/2 btn-gradient px-4 py-1 rounded-full text-xs font-black whitespace-nowrap">Most Popular</div>' if featured else ""
        tier["pricing_btn_class"]  = "btn-gradient" if featured else "btn-outline-primary"
        tier["pricing_cta"]        = "Start Free Trial" if featured else ("Get Started" if isinstance(pm, int) and pm == 0 else "Contact Sales")
        if pricing_toggle and isinstance(pm, int):
            tier["pricing_price_html"] = f'<span x-text="yearly ? \'${py}\' : \'${pm}\'"></span><span class="text-lg font-normal text-gray-400">/mo</span>'
        else:
            price_str = f"${pm}" if isinstance(pm, int) else str(pm)
            suffix    = '<span class="text-lg font-normal text-gray-400">/mo</span>' if isinstance(pm, int) else ""
            tier["pricing_price_html"] = f"<span>{price_str}</span>{suffix}"

    return ctx


# ═══════════════════════════════════════════════════════════════════════════════
# 4. PAGE ASSEMBLER
# ═══════════════════════════════════════════════════════════════════════════════

def assemble_page(page_key: str, page_cfg: dict, cfg: dict, plugin_injections: dict) -> str:
    """
    Assemble a complete HTML page from its sections using the template engine.
    """
    ctx = build_context(cfg, page_key)
    ctx = _enrich_context(ctx, cfg)

    # Plugin slots
    ctx["plugin_head"]    = plugin_injections.get("head",    "")
    ctx["plugin_body"]    = plugin_injections.get("body",    "")
    ctx["plugin_scripts"] = plugin_injections.get("scripts", "")
    ctx["page_description"] = cfg.get("description", "")

    # Assemble body from sections
    sections = page_cfg.get("sections", [])
    body_parts = []
    for section_name in sections:
        try:
            section_html = render_file(section_name, ctx)
            body_parts.append(section_html)
        except FileNotFoundError:
            print(f"    ⚠  Section template '{section_name}.html' not found — skipped")

    ctx["page_body"] = "\n".join(body_parts)

    # Render full page through _base.html
    return render_file("_base", ctx)


# ═══════════════════════════════════════════════════════════════════════════════
# 5. MINIFIER
# ═══════════════════════════════════════════════════════════════════════════════

def minify_html(html: str) -> str:
    """Basic HTML minification — collapse whitespace between tags."""
    html = re.sub(r'>\s+<', '><', html)
    html = re.sub(r'\s{2,}', ' ', html)
    html = re.sub(r'<!--(?!.*\[if).*?-->', '', html, flags=re.DOTALL)
    return html.strip()

def minify_css(css: str) -> str:
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.DOTALL)
    css = re.sub(r'\s+', ' ', css)
    css = re.sub(r'\s*([{};:,>~+])\s*', r'\1', css)
    return css.strip()

def minify_js(js: str) -> str:
    js = re.sub(r'//[^\n]*', '', js)
    js = re.sub(r'\s+', ' ', js)
    return js.strip()


# ═══════════════════════════════════════════════════════════════════════════════
# 6. MAIN BUILD FUNCTION
# ═══════════════════════════════════════════════════════════════════════════════

def load_config(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        cfg = json.load(f)
    cfg.setdefault("tagline",     "Build the Future Faster Than Ever")
    cfg.setdefault("description", "Cutting-edge solutions for modern teams.")
    cfg.setdefault("cta_text",    "Get Started")
    cfg.setdefault("cta_link",    "contact.html")
    cfg.setdefault("font",        "Inter")
    cfg.setdefault("pages",       {})
    cfg.setdefault("features",    {})
    cfg.setdefault("content",     {})
    cfg.setdefault("plugins",     {})
    f = cfg["features"]
    for k, v in [("dark_mode",True),("animations",True),("blog",True),("portfolio_filter",True),
                 ("pricing_toggle",True),("scroll_progress",True),("back_to_top",True),
                 ("newsletter",True),("counter_animation",True)]:
        f.setdefault(k, v)
    return cfg


def build(cfg: dict, out_dir: Path, mode: str = "static", minify: bool = False) -> list[str]:
    import plugins as plugin_loader
    from exporter import export_flask, export_react

    # Clean output
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    generated = []

    # Run plugins
    plugin_injections = plugin_loader.run_all(cfg)

    # Generate CSS + JS
    css = generate_css(cfg)
    js  = generate_js(cfg)
    if minify:
        css = minify_css(css)
        js  = minify_js(js)

    # Collect all page HTML
    pages_html: dict[str, str] = {}
    pages_cfg  = cfg.get("pages", {})

    for page_key, page_cfg in pages_cfg.items():
        # Feature gate: blog
        if page_key == "blog" and not cfg["features"].get("blog", True):
            print(f"  ⏭  blog skipped (features.blog=false)")
            continue

        filename = page_cfg.get("file", page_key + ".html")
        print(f"  ✓  {filename}")

        html = assemble_page(page_key, page_cfg, cfg, plugin_injections)
        if minify:
            html = minify_html(html)
        pages_html[filename] = html

    if mode == "flask":
        print("\n  📦 Flask export mode")
        (out_dir / "static" / "css").mkdir(parents=True, exist_ok=True)
        (out_dir / "static" / "js").mkdir(parents=True, exist_ok=True)
        (out_dir / "static" / "css" / "style.css").write_text(css, encoding="utf-8")
        (out_dir / "static" / "js"  / "script.js").write_text(js,  encoding="utf-8")
        generated += ["static/css/style.css", "static/js/script.js"]
        generated += export_flask(cfg, out_dir, pages_html)

    elif mode == "react":
        print("\n  ⚛  React export mode")
        (out_dir / "style.css").write_text(css, encoding="utf-8")
        (out_dir / "script.js").write_text(js,  encoding="utf-8")
        generated += ["style.css", "script.js"]
        generated += export_react(cfg, out_dir, pages_html)

    else:  # static (default)
        (out_dir / "style.css").write_text(css, encoding="utf-8")
        (out_dir / "script.js").write_text(js,  encoding="utf-8")
        generated += ["style.css", "script.js"]
        for filename, html in pages_html.items():
            (out_dir / filename).write_text(html, encoding="utf-8")
            generated.append(filename)

    print(f"\n✅ Built {len(generated)} files → {out_dir}  [mode={mode}{'  minified' if minify else ''}]")
    return generated


# ═══════════════════════════════════════════════════════════════════════════════
# 7. WATCH MODE
# ═══════════════════════════════════════════════════════════════════════════════

def watch(cfg_path: Path, out_dir: Path, mode: str, minify: bool) -> None:
    """Watch config + templates for changes and auto-rebuild."""
    watch_dirs  = [HERE / "templates", HERE / "plugins"]
    watch_files = [cfg_path]

    def get_mtimes():
        mtimes = {}
        for f in watch_files:
            if f.exists():
                mtimes[str(f)] = f.stat().st_mtime
        for d in watch_dirs:
            if d.exists():
                for f in d.rglob("*"):
                    if f.is_file():
                        mtimes[str(f)] = f.stat().st_mtime
        return mtimes

    print(f"👁  Watching for changes... (Ctrl+C to stop)\n")
    last = get_mtimes()

    while True:
        time.sleep(1)
        current = get_mtimes()
        changed = [k for k in current if current[k] != last.get(k)]
        if changed:
            print(f"\n🔄 Change detected: {', '.join(Path(c).name for c in changed)}")
            try:
                cfg = load_config(cfg_path)
                build(cfg, out_dir, mode, minify)
            except Exception as e:
                print(f"  ❌ Build error: {e}")
            last = get_mtimes()


# ═══════════════════════════════════════════════════════════════════════════════
# 8. PREVIEW SERVER
# ═══════════════════════════════════════════════════════════════════════════════

def serve(out_dir: Path, port: int = 8080) -> None:
    os.chdir(out_dir)
    class Handler(http.server.SimpleHTTPRequestHandler):
        def log_message(self, fmt, *args):
            print(f"  [{self.address_string()}] {fmt % args}")
    server = http.server.HTTPServer(("", port), Handler)
    print(f"\n🌐 Preview: http://localhost:{port}  (Ctrl+C to stop)\n")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n👋 Server stopped.")


# ═══════════════════════════════════════════════════════════════════════════════
# 9. CLI
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Website Builder System v2 — template engine + plugins + export modes",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  python build.py
  python build.py --config my.json --out ./dist
  python build.py --mode flask
  python build.py --mode react
  python build.py --minify
  python build.py --watch
  python build.py --preview --port 3000
  python build.py --mode flask --minify --preview
"""
    )
    parser.add_argument("--config",  default=str(DEFAULT_CONFIG), help="Config JSON path")
    parser.add_argument("--out",     default=str(DEFAULT_OUT),    help="Output directory")
    parser.add_argument("--mode",    default="static", choices=["static","flask","react"], help="Export mode")
    parser.add_argument("--minify",  action="store_true", help="Minify HTML/CSS/JS output")
    parser.add_argument("--watch",   action="store_true", help="Watch for changes and auto-rebuild")
    parser.add_argument("--preview", action="store_true", help="Start preview server after build")
    parser.add_argument("--port",    type=int, default=8080, help="Preview server port")
    args = parser.parse_args()

    cfg_path = Path(args.config)
    out_dir  = Path(args.out)

    if not cfg_path.exists():
        print(f"❌ Config not found: {cfg_path}")
        return

    print(f"📖 Config:  {cfg_path}")
    cfg = load_config(cfg_path)
    print(f"🏗  Site:    {cfg['site_name']}")
    print(f"   Mode:    {args.mode}")
    print(f"   Output:  {out_dir}")
    print(f"   Minify:  {args.minify}")
    print(f"   Pages:   {', '.join(cfg['pages'].keys())}")
    print(f"   Plugins: {', '.join(k for k,v in cfg.get('plugins',{}).items() if v.get('enabled'))}\n")

    build(cfg, out_dir, args.mode, args.minify)

    if args.watch and args.preview:
        # Preview in background thread, watch in foreground
        t = threading.Thread(target=serve, args=(out_dir, args.port), daemon=True)
        t.start()
        watch(cfg_path, out_dir, args.mode, args.minify)
    elif args.watch:
        watch(cfg_path, out_dir, args.mode, args.minify)
    elif args.preview:
        serve(out_dir, args.port)


if __name__ == "__main__":
    main()
