"""
exporter.py — Export modes for Website Builder System

Modes:
  static  — plain HTML/CSS/JS (default)
  flask   — wraps output in a Flask app.py
  react   — exports basic React components
"""

from pathlib import Path


# ═══════════════════════════════════════════════════════════════════════════════
# FLASK EXPORT
# ═══════════════════════════════════════════════════════════════════════════════

def export_flask(cfg: dict, out_dir: Path, pages: dict[str, str]) -> list[str]:
    """
    Wrap the static site in a minimal Flask app.
    - Moves HTML files to templates/
    - Generates app.py with routes for each page
    - Generates requirements.txt
    """
    name = cfg["site_name"]
    (out_dir / "templates").mkdir(exist_ok=True)
    (out_dir / "static" / "css").mkdir(parents=True, exist_ok=True)
    (out_dir / "static" / "js").mkdir(parents=True, exist_ok=True)

    generated = []

    # Move HTML → templates/
    for filename, html in pages.items():
        # Rewrite static asset paths for Flask
        html = html.replace('href="style.css"',   "href=\"{{ url_for('static', filename='css/style.css') }}\"")
        html = html.replace('src="script.js"',    "src=\"{{ url_for('static', filename='js/script.js') }}\"")
        (out_dir / "templates" / filename).write_text(html, encoding="utf-8")
        generated.append(f"templates/{filename}")

    # Build route map
    route_map = {
        "index.html":        ("/",              "home"),
        "about.html":        ("/about",         "about"),
        "services.html":     ("/services",      "services"),
        "portfolio.html":    ("/portfolio",     "portfolio"),
        "blog.html":         ("/blog",          "blog"),
        "contact.html":      ("/contact",       "contact"),
        "pricing.html":      ("/pricing",       "pricing"),
        "team.html":         ("/team",          "team"),
        "faq.html":          ("/faq",           "faq"),
        "testimonials.html": ("/testimonials",  "testimonials"),
    }

    routes = ""
    for filename in pages:
        if filename in route_map:
            path, fn = route_map[filename]
            routes += f"""
@app.route('{path}')
def {fn}():
    return render_template('{filename}')
"""

    app_py = f'''"""
app.py — {name}
Generated by Website Builder System (Flask export mode)
"""
import os
from flask import Flask, render_template, request, redirect, url_for, flash

app = Flask(__name__)
app.secret_key = os.environ.get('SECRET_KEY', 'change-this-in-production')

{routes}

@app.route('/contact', methods=['POST'])
def contact_submit():
    name    = request.form.get('firstName', '') + ' ' + request.form.get('lastName', '')
    email   = request.form.get('email', '')
    message = request.form.get('message', '')
    # TODO: send email or save to DB
    flash(f'Thanks {{name}}! We will get back to you soon.', 'success')
    return redirect(url_for('contact'))

if __name__ == '__main__':
    app.run(debug=True)
'''

    (out_dir / "app.py").write_text(app_py, encoding="utf-8")
    (out_dir / "requirements.txt").write_text("Flask==3.0.0\nWerkzeug==3.0.1\n", encoding="utf-8")
    generated += ["app.py", "requirements.txt"]

    readme = f"""{name} — Flask Export
{'=' * 40}

QUICK START
-----------
1. pip install -r requirements.txt
2. python app.py
3. Open http://localhost:5000

Generated by Website Builder System
"""
    (out_dir / "README.txt").write_text(readme, encoding="utf-8")
    generated.append("README.txt")

    return generated


# ═══════════════════════════════════════════════════════════════════════════════
# REACT EXPORT
# ═══════════════════════════════════════════════════════════════════════════════

def export_react(cfg: dict, out_dir: Path, pages: dict[str, str]) -> list[str]:
    """
    Export basic React components.
    - Creates src/pages/ with one .jsx per page
    - Creates src/App.jsx with React Router
    - Creates package.json
    """
    name    = cfg["site_name"]
    primary = cfg["primary_color"]
    second  = cfg["secondary_color"]

    (out_dir / "src" / "pages").mkdir(parents=True, exist_ok=True)
    (out_dir / "src" / "components").mkdir(exist_ok=True)
    (out_dir / "public").mkdir(exist_ok=True)

    generated = []

    # Page name map
    page_map = {
        "index.html":        "Home",
        "about.html":        "About",
        "services.html":     "Services",
        "portfolio.html":    "Portfolio",
        "blog.html":         "Blog",
        "contact.html":      "Contact",
        "pricing.html":      "Pricing",
        "team.html":         "Team",
        "faq.html":          "FAQ",
        "testimonials.html": "Testimonials",
    }

    route_map = {
        "Home": "/", "About": "/about", "Services": "/services",
        "Portfolio": "/portfolio", "Blog": "/blog", "Contact": "/contact",
        "Pricing": "/pricing", "Team": "/team", "FAQ": "/faq",
        "Testimonials": "/testimonials",
    }

    # Generate one .jsx per page (wraps raw HTML in dangerouslySetInnerHTML)
    for filename, html in pages.items():
        comp_name = page_map.get(filename, filename.replace(".html", "").title())
        # Strip <html>/<head>/<body> wrappers for component
        import re
        body_match = re.search(r'<body[^>]*>(.*?)</body>', html, re.DOTALL)
        inner = body_match.group(1).strip() if body_match else html
        # Escape backticks for template literal
        inner_escaped = inner.replace('`', '\\`').replace('${', '\\${')

        jsx = f"""// {comp_name}.jsx — Generated by Website Builder System
import React from 'react';

const {comp_name} = () => {{
  const html = `{inner_escaped}`;
  return (
    <div
      className="{comp_name.lower()}-page"
      dangerouslySetInnerHTML={{{{ __html: html }}}}
    />
  );
}};

export default {comp_name};
"""
        path = out_dir / "src" / "pages" / f"{comp_name}.jsx"
        path.write_text(jsx, encoding="utf-8")
        generated.append(f"src/pages/{comp_name}.jsx")

    # App.jsx with React Router
    imports  = "\n".join(f"import {page_map[f]} from './pages/{page_map[f]}';" for f in pages if f in page_map)
    routes_r = "\n          ".join(f'<Route path="{route_map[page_map[f]]}" element={{<{page_map[f]}/>}}/>' for f in pages if f in page_map)

    app_jsx = f"""// App.jsx — Generated by Website Builder System
import React from 'react';
import {{ BrowserRouter, Routes, Route }} from 'react-router-dom';
{imports}

function App() {{
  return (
    <BrowserRouter>
      <Routes>
          {routes_r}
      </Routes>
    </BrowserRouter>
  );
}}

export default App;
"""
    (out_dir / "src" / "App.jsx").write_text(app_jsx, encoding="utf-8")
    generated.append("src/App.jsx")

    # index.jsx
    index_jsx = """import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode><App /></React.StrictMode>
);
"""
    (out_dir / "src" / "index.jsx").write_text(index_jsx, encoding="utf-8")
    generated.append("src/index.jsx")

    # package.json
    pkg = f'''{{
  "name": "{name.lower().replace(' ', '-')}",
  "version": "1.0.0",
  "private": true,
  "scripts": {{
    "dev":   "vite",
    "build": "vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "react":        "^18.2.0",
    "react-dom":    "^18.2.0",
    "react-router-dom": "^6.22.0"
  }},
  "devDependencies": {{
    "@vitejs/plugin-react": "^4.2.0",
    "vite": "^5.0.0"
  }}
}}
'''
    (out_dir / "package.json").write_text(pkg, encoding="utf-8")
    generated.append("package.json")

    # vite.config.js
    vite = """import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
export default defineConfig({ plugins: [react()] });
"""
    (out_dir / "vite.config.js").write_text(vite, encoding="utf-8")
    generated.append("vite.config.js")

    # public/index.html
    pub_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>{name}</title>
  <style>:root{{--primary:{primary};--secondary:{second}}}</style>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/index.jsx"></script>
</body>
</html>
"""
    (out_dir / "public" / "index.html").write_text(pub_html, encoding="utf-8")
    generated.append("public/index.html")

    readme = f"""{name} — React Export
{'=' * 40}

QUICK START
-----------
1. npm install
2. npm run dev
3. Open http://localhost:5173

Generated by Website Builder System
"""
    (out_dir / "README.txt").write_text(readme, encoding="utf-8")
    generated.append("README.txt")

    return generated
