"""
_inject_shopwave.py
Patches generator.py to replace _MV_APP_PY_BODY with the complete ShopWave app.
Also updates _mv_template_functions.py with new template helpers.
Also updates _gen_ecommerce in generator.py to include new template files.
"""
import re
import os

BASE = os.path.dirname(os.path.abspath(__file__))
GENERATOR_PATH = os.path.join(BASE, "generator.py")
TEMPLATES_PATH = os.path.join(BASE, "_mv_template_functions.py")

# ─────────────────────────────────────────────────────────────────────────────
# 1. Complete ShopWave app.py body (injected as _MV_APP_PY_BODY)
# ─────────────────────────────────────────────────────────────────────────────

NEW_APP_BODY = r'''"""
app.py — __SITE_NAME__ Multi-Vendor Marketplace
Generated by WebGen Platform
Roles: Admin / Seller / Customer
13 tables, SellerProfile, shop pages, reviews, coupons,
notifications, withdrawals, order timeline, 90/10 split
"""
import os, re, uuid, sqlite3
from datetime import datetime, timedelta
from collections import defaultdict
from flask import (Flask, render_template, request, redirect,
                   url_for, session, flash, jsonify)
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename
from functools import wraps

app = Flask(__name__)
app.secret_key = os.environ.get('SECRET_KEY', 'shopwave-secret-2025')

UPLOAD_FOLDER = os.path.join('static', 'uploads')
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif', 'webp'}
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

DB_PATH = os.path.join(os.path.dirname(__file__), 'database.db')
SELLER_SHARE   = 0.90
PLATFORM_SHARE = 0.10
CATEGORIES = ['Fashion','Electronics','Home & Kitchen','Beauty','Sports','Books','Toys','General']
STATUSES   = ['pending','paid','confirmed','shipped','out_for_delivery','delivered','cancelled']

# ── Database ──────────────────────────────────────────────────────────────────

def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = get_db()
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            role TEXT DEFAULT 'customer',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS seller_profiles (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER UNIQUE NOT NULL,
            shop_name TEXT UNIQUE NOT NULL,
            shop_slug TEXT UNIQUE NOT NULL,
            logo TEXT DEFAULT 'default.png',
            description TEXT DEFAULT '',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES users(id)
        );
        CREATE TABLE IF NOT EXISTS products (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            seller_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            price REAL NOT NULL,
            stock INTEGER DEFAULT 0,
            category TEXT DEFAULT 'General',
            image TEXT DEFAULT 'default.png',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (seller_id) REFERENCES users(id)
        );
        CREATE TABLE IF NOT EXISTS cart_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            quantity INTEGER DEFAULT 1
        );
        CREATE TABLE IF NOT EXISTS orders (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            customer_id INTEGER NOT NULL,
            total_price REAL NOT NULL,
            payment_ref TEXT,
            status TEXT DEFAULT 'paid',
            address TEXT,
            coupon_code TEXT DEFAULT '',
            discount REAL DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS order_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            order_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            seller_id INTEGER NOT NULL,
            quantity INTEGER DEFAULT 1,
            price REAL NOT NULL
        );
        CREATE TABLE IF NOT EXISTS order_timeline (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            order_id INTEGER NOT NULL,
            status TEXT NOT NULL,
            note TEXT DEFAULT '',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS seller_earnings (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            seller_id INTEGER NOT NULL,
            order_id INTEGER NOT NULL,
            amount REAL NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS platform_earnings (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            order_id INTEGER NOT NULL UNIQUE,
            amount REAL NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS reviews (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            product_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            rating INTEGER NOT NULL,
            comment TEXT DEFAULT '',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(product_id, user_id)
        );
        CREATE TABLE IF NOT EXISTS coupons (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            code TEXT UNIQUE NOT NULL,
            discount_type TEXT DEFAULT 'percent',
            discount_value REAL NOT NULL,
            min_order REAL DEFAULT 0,
            max_uses INTEGER DEFAULT 0,
            used_count INTEGER DEFAULT 0,
            is_active INTEGER DEFAULT 1,
            expires_at TIMESTAMP,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS notifications (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            message TEXT NOT NULL,
            link TEXT DEFAULT '',
            is_read INTEGER DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS withdrawal_requests (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            seller_id INTEGER NOT NULL,
            amount REAL NOT NULL,
            upi_id TEXT DEFAULT '',
            status TEXT DEFAULT 'pending',
            note TEXT DEFAULT '',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    """)
    if not conn.execute("SELECT id FROM users WHERE email='admin@marketplace.com'").fetchone():
        conn.execute("INSERT INTO users (name,email,password,role) VALUES (?,?,?,?)",
                     ('Admin','admin@marketplace.com',generate_password_hash('admin123'),'admin'))
    conn.commit()
    conn.close()

def _slugify(text):
    text = text.lower().strip()
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[\s_-]+', '-', text)
    return text or 'shop'

def allowed_file(fn):
    return '.' in fn and fn.rsplit('.',1)[1].lower() in ALLOWED_EXTENSIONS

def save_image(file):
    if file and file.filename and allowed_file(file.filename):
        ext = file.filename.rsplit('.',1)[1].lower()
        fn  = uuid.uuid4().hex + '.' + ext
        file.save(os.path.join(app.config['UPLOAD_FOLDER'], fn))
        return fn
    return 'default.png'

def notify(conn, user_id, message, link=''):
    conn.execute('INSERT INTO notifications (user_id,message,link) VALUES (?,?,?)',
                 (user_id, message, link))

def record_timeline(conn, order_id, status, note=''):
    conn.execute('INSERT INTO order_timeline (order_id,status,note) VALUES (?,?,?)',
                 (order_id, status, note))

# ── Decorators ────────────────────────────────────────────────────────────────

def login_required(f):
    @wraps(f)
    def dec(*a,**kw):
        if 'user_id' not in session:
            flash('Please login first.','warning')
            return redirect(url_for('login'))
        return f(*a,**kw)
    return dec

def seller_required(f):
    @wraps(f)
    def dec(*a,**kw):
        if session.get('role') not in ('seller','admin'):
            flash('Seller access required.','error')
            return redirect(url_for('index'))
        return f(*a,**kw)
    return dec

def admin_required(f):
    @wraps(f)
    def dec(*a,**kw):
        if session.get('role') != 'admin':
            flash('Admin access required.','error')
            return redirect(url_for('index'))
        return f(*a,**kw)
    return dec

# ── Auth ──────────────────────────────────────────────────────────────────────

@app.route('/signup', methods=['GET','POST'])
def signup():
    if request.method == 'POST':
        name      = request.form['name'].strip()
        email     = request.form['email'].strip().lower()
        pw        = generate_password_hash(request.form['password'])
        role      = request.form.get('role','customer')
        shop_name = request.form.get('shop_name','').strip()
        if role not in ('seller','customer'): role = 'customer'
        if role == 'seller' and not shop_name:
            flash('Please enter your shop name.','error')
            return redirect(url_for('signup'))
        conn = get_db()
        if conn.execute('SELECT id FROM users WHERE email=?',(email,)).fetchone():
            flash('Email already registered.','error'); conn.close()
            return redirect(url_for('signup'))
        if role == 'seller':
            slug = _slugify(shop_name)
            if conn.execute('SELECT id FROM seller_profiles WHERE shop_slug=?',(slug,)).fetchone():
                flash('Shop name already taken.','error'); conn.close()
                return redirect(url_for('signup'))
        conn.execute('INSERT INTO users (name,email,password,role) VALUES (?,?,?,?)',(name,email,pw,role))
        uid = conn.execute('SELECT last_insert_rowid()').fetchone()[0]
        if role == 'seller':
            slug = _slugify(shop_name)
            conn.execute('INSERT INTO seller_profiles (user_id,shop_name,shop_slug) VALUES (?,?,?)',
                         (uid, shop_name, slug))
        conn.commit(); conn.close()
        flash('Account created! Please login.','success')
        return redirect(url_for('login'))
    return render_template('auth/signup.html')

@app.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'POST':
        email = request.form['email'].strip().lower()
        pw    = request.form['password']
        conn  = get_db()
        user  = conn.execute('SELECT * FROM users WHERE email=?',(email,)).fetchone()
        conn.close()
        if user and check_password_hash(user['password'], pw):
            session['user_id']   = user['id']
            session['user_name'] = user['name']
            session['role']      = user['role']
            if user['role'] == 'admin':  return redirect(url_for('admin_dashboard'))
            if user['role'] == 'seller': return redirect(url_for('seller_dashboard'))
            return redirect(url_for('index'))
        flash('Invalid email or password.','error')
    return render_template('auth/login.html')

@app.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('login'))

# ── Customer storefront ───────────────────────────────────────────────────────

@app.route('/')
def index():
    q=request.args.get('q','').strip(); cat=request.args.get('category','')
    minp=request.args.get('min_price',''); maxp=request.args.get('max_price','')
    sort=request.args.get('sort','newest')
    conn=get_db()
    sql="""SELECT p.*,u.name as seller_name,
               COALESCE(sp.shop_name,u.name) as shop_name,
               COALESCE(sp.shop_slug,'') as shop_slug,
               COALESCE(AVG(r.rating),0) as avg_rating,
               COUNT(r.id) as review_count
               FROM products p
               JOIN users u ON p.seller_id=u.id
               LEFT JOIN seller_profiles sp ON u.id=sp.user_id
               LEFT JOIN reviews r ON p.id=r.product_id
               WHERE p.stock>0"""
    args=[]
    if q:    sql+=' AND p.name LIKE ?'; args.append(f'%{q}%')
    if cat:  sql+=' AND p.category=?'; args.append(cat)
    if minp: sql+=' AND p.price>=?'; args.append(float(minp))
    if maxp: sql+=' AND p.price<=?'; args.append(float(maxp))
    sql+=' GROUP BY p.id'
    sql+=({'price_asc':' ORDER BY p.price ASC','price_desc':' ORDER BY p.price DESC',
           'rating':' ORDER BY avg_rating DESC'}).get(sort,' ORDER BY p.created_at DESC')
    products=conn.execute(sql,args).fetchall()
    categories=[r[0] for r in conn.execute('SELECT DISTINCT category FROM products').fetchall()]
    conn.close()
    return render_template('customer/index.html',products=products,categories=categories,
                           q=q,selected_cat=cat,min_price=minp,max_price=maxp,sort=sort)

@app.route('/product/<int:pid>')
def product_detail(pid):
    conn=get_db()
    p=conn.execute("""SELECT p.*,u.name as seller_name,
                       COALESCE(sp.shop_name,u.name) as shop_name,
                       COALESCE(sp.shop_slug,'') as shop_slug,
                       COALESCE(AVG(r.rating),0) as avg_rating,
                       COUNT(r.id) as review_count
                       FROM products p JOIN users u ON p.seller_id=u.id
                       LEFT JOIN seller_profiles sp ON u.id=sp.user_id
                       LEFT JOIN reviews r ON p.id=r.product_id
                       WHERE p.id=? GROUP BY p.id""",(pid,)).fetchone()
    if not p: conn.close(); return render_template('errors/404.html'),404
    related=conn.execute('SELECT * FROM products WHERE category=? AND id!=? AND stock>0 LIMIT 4',
                         (p['category'],pid)).fetchall()
    reviews=conn.execute("""SELECT r.*,u.name as reviewer_name FROM reviews r
                            JOIN users u ON r.user_id=u.id WHERE r.product_id=?
                            ORDER BY r.created_at DESC""",(pid,)).fetchall()
    user_review=None
    if session.get('user_id'):
        user_review=conn.execute('SELECT * FROM reviews WHERE product_id=? AND user_id=?',
                                  (pid,session['user_id'])).fetchone()
    conn.close()
    return render_template('customer/product_detail.html',product=p,related=related,
                           reviews=reviews,user_review=user_review)

@app.route('/store/<shop_slug>')
def seller_store(shop_slug):
    conn=get_db()
    sp=conn.execute('SELECT sp.*,u.name as seller_name FROM seller_profiles sp JOIN users u ON sp.user_id=u.id WHERE sp.shop_slug=?',
                    (shop_slug,)).fetchone()
    if not sp: conn.close(); return render_template('errors/404.html'),404
    q=request.args.get('q','').strip(); cat=request.args.get('category','')
    sql='SELECT * FROM products WHERE seller_id=? AND stock>0'
    args=[sp['user_id']]
    if q:   sql+=' AND name LIKE ?'; args.append(f'%{q}%')
    if cat: sql+=' AND category=?'; args.append(cat)
    sql+=' ORDER BY created_at DESC'
    products=conn.execute(sql,args).fetchall()
    cats=[r[0] for r in conn.execute('SELECT DISTINCT category FROM products WHERE seller_id=?',
                                      (sp['user_id'],)).fetchall()]
    conn.close()
    return render_template('customer/seller_store.html',profile=sp,products=products,
                           categories=cats,q=q,selected_cat=cat)

@app.route('/product/<int:pid>/review', methods=['POST'])
@login_required
def submit_review(pid):
    rating=int(request.form.get('rating',5)); comment=request.form.get('comment','').strip()
    if not 1<=rating<=5: flash('Rating must be 1-5.','error'); return redirect(url_for('product_detail',pid=pid))
    conn=get_db()
    existing=conn.execute('SELECT id FROM reviews WHERE product_id=? AND user_id=?',
                           (pid,session['user_id'])).fetchone()
    if existing:
        conn.execute('UPDATE reviews SET rating=?,comment=? WHERE id=?',(rating,comment,existing['id']))
        flash('Review updated!','success')
    else:
        conn.execute('INSERT INTO reviews (product_id,user_id,rating,comment) VALUES (?,?,?,?)',
                     (pid,session['user_id'],rating,comment))
        flash('Review submitted!','success')
    conn.commit(); conn.close()
    return redirect(url_for('product_detail',pid=pid))

@app.route('/product/<int:pid>/review/delete', methods=['POST'])
@login_required
def delete_review(pid):
    conn=get_db()
    conn.execute('DELETE FROM reviews WHERE product_id=? AND user_id=?',(pid,session['user_id']))
    conn.commit(); conn.close()
    flash('Review deleted.','info')
    return redirect(url_for('product_detail',pid=pid))

@app.route('/coupon/validate', methods=['POST'])
@login_required
def validate_coupon():
    code=request.json.get('code','').strip().upper()
    total=float(request.json.get('total',0))
    conn=get_db()
    c=conn.execute("SELECT * FROM coupons WHERE code=? AND is_active=1",(code,)).fetchone()
    conn.close()
    if not c: return jsonify({'valid':False,'message':'Invalid coupon code.'})
    if c['expires_at'] and datetime.strptime(c['expires_at'],'%Y-%m-%d %H:%M:%S') < datetime.now():
        return jsonify({'valid':False,'message':'Coupon has expired.'})
    if c['max_uses'] > 0 and c['used_count'] >= c['max_uses']:
        return jsonify({'valid':False,'message':'Coupon usage limit reached.'})
    if total < c['min_order']:
        return jsonify({'valid':False,'message':f'Minimum order ₹{c["min_order"]:.0f} required.'})
    if c['discount_type']=='percent':
        discount=round(total*c['discount_value']/100,2)
        msg=f'{c["discount_value"]:.0f}% off applied!'
    else:
        discount=min(c['discount_value'],total)
        msg=f'₹{discount:.0f} off applied!'
    return jsonify({'valid':True,'discount':discount,'message':msg,'code':code})

@app.route('/cart')
@login_required
def cart():
    conn=get_db()
    items=conn.execute("""SELECT ci.id,ci.quantity,p.name,p.price,p.image,p.stock,p.id as pid
           FROM cart_items ci JOIN products p ON ci.product_id=p.id WHERE ci.user_id=?""",
        (session['user_id'],)).fetchall()
    total=sum(i['price']*i['quantity'] for i in items)
    conn.close()
    return render_template('customer/cart.html',items=items,total=total)

@app.route('/cart/add/<int:pid>', methods=['POST'])
@login_required
def add_to_cart(pid):
    qty=max(1,int(request.form.get('quantity',1)))
    conn=get_db()
    p=conn.execute('SELECT * FROM products WHERE id=?',(pid,)).fetchone()
    if not p or p['stock']<1:
        flash('Product unavailable.','error'); conn.close(); return redirect(url_for('index'))
    ex=conn.execute('SELECT * FROM cart_items WHERE user_id=? AND product_id=?',
                    (session['user_id'],pid)).fetchone()
    if ex:
        conn.execute('UPDATE cart_items SET quantity=? WHERE id=?',
                     (min(ex['quantity']+qty,p['stock']),ex['id']))
    else:
        conn.execute('INSERT INTO cart_items (user_id,product_id,quantity) VALUES (?,?,?)',
                     (session['user_id'],pid,min(qty,p['stock'])))
    conn.commit(); conn.close()
    flash(f'"{p["name"]}" added to cart.','success')
    return redirect(request.referrer or url_for('cart'))

@app.route('/cart/update/<int:iid>', methods=['POST'])
@login_required
def update_cart(iid):
    qty=int(request.form.get('quantity',1))
    conn=get_db()
    if qty<1: conn.execute('DELETE FROM cart_items WHERE id=? AND user_id=?',(iid,session['user_id']))
    else: conn.execute('UPDATE cart_items SET quantity=? WHERE id=? AND user_id=?',(qty,iid,session['user_id']))
    conn.commit(); conn.close()
    return redirect(url_for('cart'))

@app.route('/cart/remove/<int:iid>', methods=['POST'])
@login_required
def remove_from_cart(iid):
    conn=get_db()
    conn.execute('DELETE FROM cart_items WHERE id=? AND user_id=?',(iid,session['user_id']))
    conn.commit(); conn.close()
    flash('Item removed.','info')
    return redirect(url_for('cart'))

@app.route('/checkout', methods=['GET','POST'])
@login_required
def checkout():
    conn=get_db()
    items=conn.execute("""SELECT ci.id,ci.quantity,p.id as pid,p.name,p.price,p.stock,p.seller_id
           FROM cart_items ci JOIN products p ON ci.product_id=p.id WHERE ci.user_id=?""",
        (session['user_id'],)).fetchall()
    if not items:
        flash('Your cart is empty.','warning'); conn.close(); return redirect(url_for('cart'))
    subtotal=sum(i['price']*i['quantity'] for i in items)
    if request.method=='POST':
        address=request.form.get('address','').strip()
        coupon_code=request.form.get('coupon_code','').strip().upper()
        discount=float(request.form.get('discount',0))
        if not address:
            flash('Please enter a delivery address.','error'); conn.close()
            return redirect(url_for('checkout'))
        total=max(0,subtotal-discount)
        ref='PAY-'+uuid.uuid4().hex[:10].upper()
        conn.execute('INSERT INTO orders (customer_id,total_price,payment_ref,status,address,coupon_code,discount) VALUES (?,?,?,?,?,?,?)',
                     (session['user_id'],total,ref,'paid',address,coupon_code,discount))
        oid=conn.execute('SELECT last_insert_rowid()').fetchone()[0]
        record_timeline(conn,oid,'paid','Order placed and payment received.')
        seller_totals={}
        for i in items:
            conn.execute('INSERT INTO order_items (order_id,product_id,seller_id,quantity,price) VALUES (?,?,?,?,?)',
                         (oid,i['pid'],i['seller_id'],i['quantity'],i['price']))
            conn.execute('UPDATE products SET stock=MAX(0,stock-?) WHERE id=?',(i['quantity'],i['pid']))
            seller_totals[i['seller_id']]=seller_totals.get(i['seller_id'],0)+i['price']*i['quantity']
        for sid,amt in seller_totals.items():
            share=round(amt*(1-discount/subtotal if subtotal else 1)*SELLER_SHARE,2)
            conn.execute('INSERT INTO seller_earnings (seller_id,order_id,amount) VALUES (?,?,?)',(sid,oid,share))
            notify(conn,sid,f'New order #{oid} received! ₹{share:.2f} credited.',url_for('seller_orders'))
        conn.execute('INSERT INTO platform_earnings (order_id,amount) VALUES (?,?)',
                     (oid,round(total*PLATFORM_SHARE,2)))
        if coupon_code:
            conn.execute('UPDATE coupons SET used_count=used_count+1 WHERE code=?',(coupon_code,))
        conn.execute('DELETE FROM cart_items WHERE user_id=?',(session['user_id'],))
        conn.commit(); conn.close()
        flash(f'Order placed! Ref: {ref}','success')
        return redirect(url_for('order_detail',oid=oid))
    conn.close()
    return render_template('customer/checkout.html',items=items,total=subtotal)

@app.route('/orders')
@login_required
def my_orders():
    conn=get_db()
    orders=conn.execute('SELECT * FROM orders WHERE customer_id=? ORDER BY created_at DESC',
                        (session['user_id'],)).fetchall()
    conn.close()
    return render_template('customer/orders.html',orders=orders)

@app.route('/orders/<int:oid>')
@login_required
def order_detail(oid):
    conn=get_db()
    order=conn.execute('SELECT * FROM orders WHERE id=? AND customer_id=?',
                       (oid,session['user_id'])).fetchone()
    if not order: conn.close(); return render_template('errors/404.html'),404
    items=conn.execute("""SELECT oi.*,p.name,p.image FROM order_items oi
                          JOIN products p ON oi.product_id=p.id WHERE oi.order_id=?""",(oid,)).fetchall()
    timeline=conn.execute('SELECT * FROM order_timeline WHERE order_id=? ORDER BY created_at ASC',(oid,)).fetchall()
    conn.close()
    return render_template('customer/order_detail.html',order=order,items=items,timeline=timeline)

@app.route('/notifications')
@login_required
def notifications():
    conn=get_db()
    notifs=conn.execute('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC',
                        (session['user_id'],)).fetchall()
    conn.execute('UPDATE notifications SET is_read=1 WHERE user_id=?',(session['user_id'],))
    conn.commit(); conn.close()
    return render_template('customer/notifications.html',notifications=notifs)

# ── Seller routes ─────────────────────────────────────────────────────────────

@app.route('/seller/dashboard')
@login_required
@seller_required
def seller_dashboard():
    conn=get_db()
    products=conn.execute('SELECT * FROM products WHERE seller_id=? ORDER BY created_at DESC',
                          (session['user_id'],)).fetchall()
    total_orders=conn.execute("""SELECT COUNT(DISTINCT oi.order_id) FROM order_items oi
                                  WHERE oi.seller_id=?""",(session['user_id'],)).fetchone()[0]
    total_earned=conn.execute('SELECT COALESCE(SUM(amount),0) FROM seller_earnings WHERE seller_id=?',
                               (session['user_id'],)).fetchone()[0]
    recent=conn.execute("""SELECT o.*,u.name as customer_name FROM orders o
                            JOIN order_items oi ON o.id=oi.order_id
                            JOIN users u ON o.customer_id=u.id
                            WHERE oi.seller_id=? GROUP BY o.id ORDER BY o.created_at DESC LIMIT 5""",
                        (session['user_id'],)).fetchall()
    conn.close()
    return render_template('seller/dashboard.html',products=products,total_orders=total_orders,
                           total_earned=total_earned,recent=recent)

@app.route('/seller/product/add', methods=['GET','POST'])
@login_required
@seller_required
def seller_add_product():
    if request.method=='POST':
        name=request.form['name'].strip(); desc=request.form.get('description','')
        price=float(request.form['price']); stock=int(request.form['stock'])
        cat=request.form.get('category','General')
        img=save_image(request.files.get('image'))
        conn=get_db()
        conn.execute('INSERT INTO products (seller_id,name,description,price,stock,category,image) VALUES (?,?,?,?,?,?,?)',
                     (session['user_id'],name,desc,price,stock,cat,img))
        conn.commit(); conn.close()
        flash('Product added!','success')
        return redirect(url_for('seller_dashboard'))
    return render_template('seller/product_form.html',product=None,categories=CATEGORIES)

@app.route('/seller/product/edit/<int:pid>', methods=['GET','POST'])
@login_required
@seller_required
def seller_edit_product(pid):
    conn=get_db()
    p=conn.execute('SELECT * FROM products WHERE id=? AND seller_id=?',(pid,session['user_id'])).fetchone()
    if not p: conn.close(); flash('Not found.','error'); return redirect(url_for('seller_dashboard'))
    if request.method=='POST':
        name=request.form['name'].strip(); desc=request.form.get('description','')
        price=float(request.form['price']); stock=int(request.form['stock'])
        cat=request.form.get('category','General')
        img=save_image(request.files.get('image'))
        if img=='default.png' and p['image']!='default.png': img=p['image']
        conn.execute('UPDATE products SET name=?,description=?,price=?,stock=?,category=?,image=? WHERE id=?',
                     (name,desc,price,stock,cat,img,pid))
        conn.commit(); conn.close()
        flash('Product updated!','success')
        return redirect(url_for('seller_dashboard'))
    conn.close()
    return render_template('seller/product_form.html',product=p,categories=CATEGORIES)

@app.route('/seller/product/delete/<int:pid>', methods=['POST'])
@login_required
@seller_required
def seller_delete_product(pid):
    conn=get_db()
    conn.execute('DELETE FROM products WHERE id=? AND seller_id=?',(pid,session['user_id']))
    conn.commit(); conn.close()
    flash('Product deleted.','success')
    return redirect(url_for('seller_dashboard'))

@app.route('/seller/orders')
@login_required
@seller_required
def seller_orders():
    conn=get_db()
    pids=[r[0] for r in conn.execute('SELECT id FROM products WHERE seller_id=?',(session['user_id'],)).fetchall()]
    orders=[]
    if pids:
        rows=conn.execute("""SELECT DISTINCT o.*,u.name as customer_name FROM orders o
                              JOIN order_items oi ON o.id=oi.order_id
                              JOIN users u ON o.customer_id=u.id
                              WHERE oi.seller_id=? ORDER BY o.created_at DESC""",(session['user_id'],)).fetchall()
        for o in rows:
            items=conn.execute("""SELECT oi.*,p.name,p.image FROM order_items oi
                                   JOIN products p ON oi.product_id=p.id
                                   WHERE oi.order_id=? AND oi.seller_id=?""",(o['id'],session['user_id'])).fetchall()
            orders.append({'order':o,'items':items})
    conn.close()
    return render_template('seller/orders.html',orders=orders,pids=pids)

@app.route('/seller/orders/<int:oid>/status', methods=['POST'])
@login_required
@seller_required
def seller_update_status(oid):
    status=request.form['status']
    conn=get_db()
    conn.execute('UPDATE orders SET status=? WHERE id=?',(status,oid))
    record_timeline(conn,oid,status,f'Status updated to {status} by seller.')
    order=conn.execute('SELECT * FROM orders WHERE id=?',(oid,)).fetchone()
    if order:
        notify(conn,order['customer_id'],f'Your order #{oid} is now {status}.',url_for('order_detail',oid=oid))
    conn.commit(); conn.close()
    flash('Order status updated.','success')
    return redirect(url_for('seller_orders'))

@app.route('/seller/earnings')
@login_required
@seller_required
def seller_earnings():
    conn=get_db()
    rows=conn.execute("""SELECT se.*,o.total_price,o.created_at,u.name as customer_name
                          FROM seller_earnings se JOIN orders o ON se.order_id=o.id
                          JOIN users u ON o.customer_id=u.id
                          WHERE se.seller_id=? ORDER BY se.created_at DESC""",(session['user_id'],)).fetchall()
    total=sum(r['amount'] for r in rows)
    pending_withdrawal=conn.execute("SELECT COALESCE(SUM(amount),0) FROM withdrawal_requests WHERE seller_id=? AND status='pending'",
                                     (session['user_id'],)).fetchone()[0]
    conn.close()
    return render_template('seller/earnings.html',rows=rows,total=total,pending_withdrawal=pending_withdrawal)

@app.route('/seller/profile', methods=['GET','POST'])
@login_required
@seller_required
def seller_shop_profile():
    conn=get_db()
    sp=conn.execute('SELECT * FROM seller_profiles WHERE user_id=?',(session['user_id'],)).fetchone()
    if request.method=='POST':
        shop_name=request.form.get('shop_name','').strip()
        desc=request.form.get('description','').strip()
        logo=save_image(request.files.get('logo'))
        if logo=='default.png' and sp and sp['logo']!='default.png': logo=sp['logo']
        if sp:
            conn.execute('UPDATE seller_profiles SET shop_name=?,description=?,logo=? WHERE user_id=?',
                         (shop_name,desc,logo,session['user_id']))
        else:
            slug=_slugify(shop_name)
            conn.execute('INSERT INTO seller_profiles (user_id,shop_name,shop_slug,logo,description) VALUES (?,?,?,?,?)',
                         (session['user_id'],shop_name,slug,logo,desc))
        conn.commit()
        sp=conn.execute('SELECT * FROM seller_profiles WHERE user_id=?',(session['user_id'],)).fetchone()
        conn.close()
        flash('Shop profile updated!','success')
        return redirect(url_for('seller_shop_profile'))
    conn.close()
    return render_template('seller/shop_profile.html',profile=sp)

@app.route('/seller/withdraw', methods=['POST'])
@login_required
@seller_required
def request_withdrawal():
    amount=float(request.form.get('amount',0))
    upi_id=request.form.get('upi_id','').strip()
    if amount<=0: flash('Invalid amount.','error'); return redirect(url_for('seller_earnings'))
    conn=get_db()
    total_earned=conn.execute('SELECT COALESCE(SUM(amount),0) FROM seller_earnings WHERE seller_id=?',
                               (session['user_id'],)).fetchone()[0]
    withdrawn=conn.execute("SELECT COALESCE(SUM(amount),0) FROM withdrawal_requests WHERE seller_id=? AND status!='rejected'",
                            (session['user_id'],)).fetchone()[0]
    available=total_earned-withdrawn
    if amount>available:
        flash(f'Insufficient balance. Available: ₹{available:.2f}','error'); conn.close()
        return redirect(url_for('seller_earnings'))
    conn.execute('INSERT INTO withdrawal_requests (seller_id,amount,upi_id) VALUES (?,?,?)',
                 (session['user_id'],amount,upi_id))
    conn.commit(); conn.close()
    flash(f'Withdrawal request of ₹{amount:.2f} submitted.','success')
    return redirect(url_for('seller_earnings'))

# ── Admin routes ──────────────────────────────────────────────────────────────

@app.route('/admin/dashboard')
@login_required
@admin_required
def admin_dashboard():
    conn=get_db()
    stats={
        'users':conn.execute('SELECT COUNT(*) FROM users').fetchone()[0],
        'sellers':conn.execute("SELECT COUNT(*) FROM users WHERE role='seller'").fetchone()[0],
        'products':conn.execute('SELECT COUNT(*) FROM products').fetchone()[0],
        'orders':conn.execute('SELECT COUNT(*) FROM orders').fetchone()[0],
        'revenue':conn.execute('SELECT COALESCE(SUM(total_price),0) FROM orders').fetchone()[0],
        'seller_payouts':conn.execute('SELECT COALESCE(SUM(amount),0) FROM seller_earnings').fetchone()[0],
        'platform_income':conn.execute('SELECT COALESCE(SUM(amount),0) FROM platform_earnings').fetchone()[0]
    }
    recent=conn.execute("""SELECT o.*,u.name as customer_name FROM orders o
                            JOIN users u ON o.customer_id=u.id
                            ORDER BY o.created_at DESC LIMIT 10""",(session['user_id'],)).fetchall()
    # Daily revenue last 7 days
    daily_revenue=[]
    for i in range(6,-1,-1):
        date=(datetime.now()-timedelta(days=i)).strftime('%Y-%m-%d')
        rev=conn.execute("SELECT COALESCE(SUM(total_price),0) FROM orders WHERE DATE(created_at)=?",(date,)).fetchone()[0]
        daily_revenue.append({'date':date,'revenue':rev})
    # Top products
    top_products=conn.execute("""SELECT p.name,SUM(oi.quantity) as sold FROM order_items oi
                                  JOIN products p ON oi.product_id=p.id
                                  GROUP BY p.id ORDER BY sold DESC LIMIT 5""").fetchall()
    # Top sellers
    top_sellers=conn.execute("""SELECT u.name,COALESCE(sp.shop_name,u.name) as shop_name,SUM(se.amount) as earned
                                 FROM seller_earnings se JOIN users u ON se.seller_id=u.id
                                 LEFT JOIN seller_profiles sp ON u.id=sp.user_id
                                 GROUP BY u.id ORDER BY earned DESC LIMIT 5""").fetchall()
    conn.close()
    return render_template('admin/dashboard.html',stats=stats,recent=recent,
                           daily_revenue=daily_revenue,top_products=top_products,top_sellers=top_sellers)

@app.route('/admin/users')
@login_required
@admin_required
def admin_users():
    conn=get_db()
    users=conn.execute('SELECT * FROM users ORDER BY created_at DESC').fetchall()
    conn.close()
    return render_template('admin/users.html',users=users)

@app.route('/admin/users/<int:uid>/delete', methods=['POST'])
@login_required
@admin_required
def admin_delete_user(uid):
    conn=get_db()
    conn.execute('DELETE FROM users WHERE id=? AND role!=?',(uid,'admin'))
    conn.commit(); conn.close()
    flash('User deleted.','success')
    return redirect(url_for('admin_users'))

@app.route('/admin/sellers')
@login_required
@admin_required
def admin_sellers():
    conn=get_db()
    sellers=conn.execute("""SELECT u.*,sp.shop_name,sp.shop_slug,sp.logo,sp.description
                             FROM users u LEFT JOIN seller_profiles sp ON u.id=sp.user_id
                             WHERE u.role='seller' ORDER BY u.created_at DESC""").fetchall()
    conn.close()
    return render_template('admin/sellers.html',sellers=sellers)

@app.route('/admin/products')
@login_required
@admin_required
def admin_products():
    conn=get_db()
    products=conn.execute("""SELECT p.*,u.name as seller_name FROM products p
                              JOIN users u ON p.seller_id=u.id
                              ORDER BY p.created_at DESC""").fetchall()
    conn.close()
    return render_template('admin/products.html',products=products)

@app.route('/admin/products/<int:pid>/delete', methods=['POST'])
@login_required
@admin_required
def admin_delete_product(pid):
    conn=get_db()
    conn.execute('DELETE FROM products WHERE id=?',(pid,))
    conn.commit(); conn.close()
    flash('Product deleted.','success')
    return redirect(url_for('admin_products'))

@app.route('/admin/orders')
@login_required
@admin_required
def admin_orders():
    conn=get_db()
    orders=conn.execute("""SELECT o.*,u.name as customer_name FROM orders o
                            JOIN users u ON o.customer_id=u.id
                            ORDER BY o.created_at DESC""").fetchall()
    conn.close()
    return render_template('admin/orders.html',orders=orders)

@app.route('/admin/orders/<int:oid>/status', methods=['POST'])
@login_required
@admin_required
def admin_update_status(oid):
    status=request.form['status']
    conn=get_db()
    conn.execute('UPDATE orders SET status=? WHERE id=?',(status,oid))
    record_timeline(conn,oid,status,f'Status updated to {status} by admin.')
    order=conn.execute('SELECT * FROM orders WHERE id=?',(oid,)).fetchone()
    if order:
        notify(conn,order['customer_id'],f'Your order #{oid} is now {status}.',url_for('order_detail',oid=oid))
    conn.commit(); conn.close()
    flash('Order status updated.','success')
    return redirect(url_for('admin_orders'))

@app.route('/admin/earnings')
@login_required
@admin_required
def admin_earnings():
    conn=get_db()
    rows=conn.execute("""SELECT pe.*,o.payment_ref,o.created_at,u.name as customer_name,o.total_price
                          FROM platform_earnings pe JOIN orders o ON pe.order_id=o.id
                          JOIN users u ON o.customer_id=u.id
                          ORDER BY pe.created_at DESC""").fetchall()
    total=sum(r['amount'] for r in rows)
    seller_summary=conn.execute("""SELECT u.name,u.email,SUM(se.amount) as total_s
                                    FROM seller_earnings se JOIN users u ON se.seller_id=u.id
                                    GROUP BY u.id ORDER BY total_s DESC""").fetchall()
    conn.close()
    return render_template('admin/earnings.html',rows=rows,total=total,seller_summary=seller_summary)

@app.route('/admin/coupons')
@login_required
@admin_required
def admin_coupons():
    conn=get_db()
    coupons=conn.execute('SELECT * FROM coupons ORDER BY created_at DESC').fetchall()
    conn.close()
    return render_template('admin/coupons.html',coupons=coupons)

@app.route('/admin/coupons/add', methods=['POST'])
@login_required
@admin_required
def admin_add_coupon():
    code=request.form['code'].strip().upper()
    dtype=request.form.get('discount_type','percent')
    dval=float(request.form['discount_value'])
    min_order=float(request.form.get('min_order',0))
    max_uses=int(request.form.get('max_uses',0))
    expires=request.form.get('expires_at','').strip() or None
    conn=get_db()
    try:
        conn.execute('INSERT INTO coupons (code,discount_type,discount_value,min_order,max_uses,expires_at) VALUES (?,?,?,?,?,?)',
                     (code,dtype,dval,min_order,max_uses,expires))
        conn.commit(); flash('Coupon created!','success')
    except Exception: flash('Coupon code already exists.','error')
    conn.close()
    return redirect(url_for('admin_coupons'))

@app.route('/admin/coupons/<int:cid>/toggle', methods=['POST'])
@login_required
@admin_required
def admin_toggle_coupon(cid):
    conn=get_db()
    conn.execute('UPDATE coupons SET is_active=1-is_active WHERE id=?',(cid,))
    conn.commit(); conn.close()
    return redirect(url_for('admin_coupons'))

@app.route('/admin/coupons/<int:cid>/delete', methods=['POST'])
@login_required
@admin_required
def admin_delete_coupon(cid):
    conn=get_db()
    conn.execute('DELETE FROM coupons WHERE id=?',(cid,))
    conn.commit(); conn.close()
    flash('Coupon deleted.','success')
    return redirect(url_for('admin_coupons'))

@app.route('/admin/withdrawals')
@login_required
@admin_required
def admin_withdrawals():
    conn=get_db()
    reqs=conn.execute("""SELECT wr.*,u.name as seller_name,u.email FROM withdrawal_requests wr
                          JOIN users u ON wr.seller_id=u.id
                          ORDER BY wr.created_at DESC""").fetchall()
    conn.close()
    return render_template('admin/withdrawals.html',requests=reqs)

@app.route('/admin/withdrawals/<int:rid>/action', methods=['POST'])
@login_required
@admin_required
def admin_withdrawal_action(rid):
    action=request.form['action']; note=request.form.get('note','')
    status='approved' if action=='approve' else 'rejected'
    conn=get_db()
    wr=conn.execute('SELECT * FROM withdrawal_requests WHERE id=?',(rid,)).fetchone()
    conn.execute('UPDATE withdrawal_requests SET status=?,note=? WHERE id=?',(status,note,rid))
    if wr:
        notify(conn,wr['seller_id'],f'Your withdrawal of ₹{wr["amount"]:.2f} was {status}.',url_for('seller_earnings'))
    conn.commit(); conn.close()
    flash(f'Withdrawal {status}.','success')
    return redirect(url_for('admin_withdrawals'))

@app.route('/admin/reviews')
@login_required
@admin_required
def admin_reviews():
    conn=get_db()
    reviews=conn.execute("""SELECT r.*,u.name as reviewer_name,p.name as product_name
                             FROM reviews r JOIN users u ON r.user_id=u.id
                             JOIN products p ON r.product_id=p.id
                             ORDER BY r.created_at DESC""").fetchall()
    conn.close()
    return render_template('admin/reviews.html',reviews=reviews)

@app.route('/admin/reviews/<int:rid>/delete', methods=['POST'])
@login_required
@admin_required
def admin_delete_review(rid):
    conn=get_db()
    conn.execute('DELETE FROM reviews WHERE id=?',(rid,))
    conn.commit(); conn.close()
    flash('Review deleted.','success')
    return redirect(url_for('admin_reviews'))

if __name__ == '__main__':
    init_db()
    app.run(debug=True)
'''

# ─────────────────────────────────────────────────────────────────────────────
# 2. New template functions to add to _mv_template_functions.py
# ─────────────────────────────────────────────────────────────────────────────

NEW_SIGNUP_HTML_FUNC = '''
def _mv_signup_html() -> str:
    return """{%- extends 'base.html' %}
{%- block title %}Create Account{%- endblock %}
{%- block content %}
<div class="mv-auth">
  <div class="mv-auth-card">
    <h2>Create Account</h2>
    <p class="subtitle">Join as a seller or customer</p>
    <form method="POST" action="{{ url_for('signup') }}" id="signupForm">
      <div class="mv-form-