# ShopWave complete app.py body
# This file is read by _inject_shopwave.py and injected into generator.py

SHOPWAVE_APP_HEADER = '''"""
app.py — __SITE_NAME__ Multi-Vendor Marketplace
Generated by WebGen Platform
Roles: Admin / Seller / Customer
Features: SellerProfile, shop pages, reviews, coupons,
          notifications, wallet/withdrawals, order timeline,
          payment split 90/10
"""
import os, re, uuid, sqlite3
from datetime import datetime
from collections import defaultdict
from flask import (Flask, render_template, request, redirect,
                   url_for, session, flash, jsonify, abort)
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename
from functools import wraps

app = Flask(__name__)
app.secret_key = os.environ.get(\'SECRET_KEY\', \'shopwave-secret-2025\')

UPLOAD_FOLDER = os.path.join(\'static\', \'uploads\')
ALLOWED_EXTENSIONS = {\'png\', \'jpg\', \'jpeg\', \'gif\', \'webp\'}
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
app.config[\'UPLOAD_FOLDER\'] = UPLOAD_FOLDER

DB_PATH = os.path.join(os.path.dirname(__file__), \'database.db\')
SELLER_SHARE   = 0.90
PLATFORM_SHARE = 0.10
CATEGORIES = [\'Fashion\',\'Electronics\',\'Home & Kitchen\',\'Beauty\',\'Sports\',\'Books\',\'Toys\',\'General\']
STATUSES   = [\'pending\',\'paid\',\'confirmed\',\'shipped\',\'out_for_delivery\',\'delivered\',\'cancelled\']
'''

SHOPWAVE_APP_DB = '''
# ── Database ──────────────────────────────────────────────────────────────────

def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = get_db()
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            role TEXT DEFAULT \'customer\',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS seller_profiles (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER UNIQUE NOT NULL,
            shop_name TEXT UNIQUE NOT NULL,
            shop_slug TEXT UNIQUE NOT NULL,
            logo TEXT DEFAULT \'default.png\',
            description TEXT DEFAULT \'\',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES users(id)
        );
        CREATE TABLE IF NOT EXISTS products (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            seller_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            price REAL NOT NULL,
            stock INTEGER DEFAULT 0,
            category TEXT DEFAULT \'General\',
            image TEXT DEFAULT \'default.png\',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (seller_id) REFERENCES users(id)
        );
        CREATE TABLE IF NOT EXISTS cart_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            quantity INTEGER DEFAULT 1
        );
        CREATE TABLE IF NOT EXISTS orders (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            customer_id INTEGER NOT NULL,
            total_price REAL NOT NULL,
            payment_ref TEXT,
            status TEXT DEFAULT \'paid\',
            address TEXT,
            coupon_code TEXT,
            discount REAL DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS order_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            order_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            seller_id INTEGER NOT NULL,
            quantity INTEGER DEFAULT 1,
            price REAL NOT NULL
        );
        CREATE TABLE IF NOT EXISTS order_timeline (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            order_id INTEGER NOT NULL,
            status TEXT NOT NULL,
            note TEXT DEFAULT \'\',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS seller_earnings (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            seller_id INTEGER NOT NULL,
            order_id INTEGER NOT NULL,
            amount REAL NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS platform_earnings (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            order_id INTEGER NOT NULL UNIQUE,
            amount REAL NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS reviews (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            product_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            rating INTEGER NOT NULL,
            comment TEXT DEFAULT \'\',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(product_id, user_id)
        );
        CREATE TABLE IF NOT EXISTS coupons (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            code TEXT UNIQUE NOT NULL,
            discount_type TEXT DEFAULT \'percent\',
            discount_value REAL NOT NULL,
            min_order REAL DEFAULT 0,
            max_uses INTEGER DEFAULT 0,
            used_count INTEGER DEFAULT 0,
            is_active INTEGER DEFAULT 1,
            expires_at TIMESTAMP,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS notifications (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            message TEXT NOT NULL,
            link TEXT DEFAULT \'\',
            is_read INTEGER DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS withdrawal_requests (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            seller_id INTEGER NOT NULL,
            amount REAL NOT NULL,
            upi_id TEXT DEFAULT \'\',
            status TEXT DEFAULT \'pending\',
            note TEXT DEFAULT \'\',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    """)
    if not conn.execute("SELECT id FROM users WHERE email=\'admin@marketplace.com\'").fetchone():
        conn.execute("INSERT INTO users (name,email,password,role) VALUES (?,?,?,?)",
                     (\'Admin\',\'admin@marketplace.com\',generate_password_hash(\'admin123\'),\'admin\'))
    conn.commit()
    conn.close()

def _slugify(text):
    text = text.lower().strip()
    text = re.sub(r\'[^\\w\\s-]\', \'\', text)
    text = re.sub(r\'[\\s_-]+\', \'-\', text)
    return text or \'shop\'

def allowed_file(fn):
    return \'.\' in fn and fn.rsplit(\'.\',1)[1].lower() in ALLOWED_EXTENSIONS

def save_image(file):
    if file and file.filename and allowed_file(file.filename):
        ext = file.filename.rsplit(\'.\',1)[1].lower()
        fn  = uuid.uuid4().hex + \'.\' + ext
        file.save(os.path.join(app.config[\'UPLOAD_FOLDER\'], fn))
        return fn
    return \'default.png\'

def notify(conn, user_id, message, link=\'\'):
    conn.execute(\'INSERT INTO notifications (user_id,message,link) VALUES (?,?,?)\',
                 (user_id, message, link))

def record_timeline(conn, order_id, status, note=\'\'):
    conn.execute(\'INSERT INTO order_timeline (order_id,status,note) VALUES (?,?,?)\',
                 (order_id, status, note))
'''

SHOPWAVE_APP_DECORATORS = '''
# ── Decorators ────────────────────────────────────────────────────────────────

def login_required(f):
    @wraps(f)
    def dec(*a,**kw):
        if \'user_id\' not in session:
            flash(\'Please login first.\',\'warning\')
            return redirect(url_for(\'login\'))
        return f(*a,**kw)
    return dec

def seller_required(f):
    @wraps(f)
    def dec(*a,**kw):
        if session.get(\'role\') not in (\'seller\',\'admin\'):
            flash(\'Seller access required.\',\'error\')
            return redirect(url_for(\'index\'))
        return f(*a,**kw)
    return dec

def admin_required(f):
    @wraps(f)
    def dec(*a,**kw):
        if session.get(\'role\') != \'admin\':
            flash(\'Admin access required.\',\'error\')
            return redirect(url_for(\'index\'))
        return f(*a,**kw)
    return dec
'''

SHOPWAVE_APP_AUTH = '''
# ── Auth ──────────────────────────────────────────────────────────────────────

@app.route(\'/signup\', methods=[\'GET\',\'POST\'])
def signup():
    if request.method == \'POST\':
        name      = request.form[\'name\'].strip()
        email     = request.form[\'email\'].strip().lower()
        pw        = generate_password_hash(request.form[\'password\'])
        role      = request.form.get(\'role\',\'customer\')
        shop_name = request.form.get(\'shop_name\',\'\').strip()
        if role not in (\'seller\',\'customer\'): role = \'customer\'
        if role == \'seller\' and not shop_name:
            flash(\'Please enter your shop name.\',\'error\')
            return redirect(url_for(\'signup\'))
        conn = get_db()
        if conn.execute(\'SELECT id FROM users WHERE email=?\', (email,)).fetchone():
            flash(\'Email already registered.\',\'error\'); conn.close()
            return redirect(url_for(\'signup\'))
        if role == \'seller\':
            slug = _slugify(shop_name)
            if conn.execute(\'SELECT id FROM seller_profiles WHERE shop_slug=?\', (slug,)).fetchone():
                flash(\'Shop name already taken.\',\'error\'); conn.close()
                return redirect(url_for(\'signup\'))
        conn.execute(\'INSERT INTO users (name,email,password,role) VALUES (?,?,?,?)\', (name,email,pw,role))
        uid = conn.execute(\'SELECT last_insert_rowid()\').fetchone()[0]
        if role == \'seller\':
            slug = _slugify(shop_name)
            conn.execute(\'INSERT INTO seller_profiles (user_id,shop_name,shop_slug) VALUES (?,?,?)\',
                         (uid, shop_name, slug))
        conn.commit(); conn.close()
        flash(\'Account created! Please login.\',\'success\')
        return redirect(url_for(\'login\'))
    return render_template(\'auth/signup.html\')

@app.route(\'/login\', methods=[\'GET\',\'POST\'])
def login():
    if request.method == \'POST\':
        email = request.form[\'email\'].strip().lower()
        pw    = request.form[\'password\']
        conn  = get_db()
        user  = conn.execute(\'SELECT * FROM users WHERE email=?\', (email,)).fetchone()
        conn.close()
        if user and check_password_hash(user[\'password\'], pw):
            session[\'user_id\']   = user[\'id\']
            session[\'user_name\'] = user[\'name\']
            session[\'role\']      = user[\'role\']
            if user[\'role\'] == \'admin\':   return redirect(url_for(\'admin_dashboard\'))
            if user[\'role\'] == \'seller\':  return redirect(url_for(\'seller_dashboard\'))
            return redirect(url_for(\'index\'))
        flash(\'Invalid email or password.\',\'error\')
    return render_template(\'auth/login.html\')

@app.route(\'/logout\')
def logout():
    session.clear()
    return redirect(url_for(\'login\'))
'''

SHOPWAVE_APP_CUSTOMER = '''
# ── Customer storefront ───────────────────────────────────────────────────────

@app.route(\'/\')
def index():
    q=request.args.get(\'q\',\'\').strip(); cat=request.args.get(\'category\',\'\')
    minp=request.args.get(\'min_price\',\'\'); maxp=request.args.get(\'max_price\',\'\')
    sort=request.args.get(\'sort\',\'newest\')
    conn=get_db()
    sql=\'\'\'SELECT p.*,u.name as seller_name,
               COALESCE(sp.shop_name,u.name) as shop_name,
               COALESCE(sp.shop_slug,\\\'\\\') as shop_slug,
               COALESCE(AVG(r.rating),0) as avg_rating,
               COUNT(r.id) as review_count
               FROM products p
               JOIN users u ON p.seller_id=u.id
               LEFT JOIN seller_profiles sp ON u.id=sp.user_id
               LEFT JOIN reviews r ON p.id=r.product_id
               WHERE p.stock>0\'\'\'
    args=[]
    if q:    sql+=\' AND p.name LIKE ?\'; args.append(f\'%{q}%\')
    if cat:  sql+=\' AND p.category=?\'; args.append(cat)
    if minp: sql+=\' AND p.price>=?\'; args.append(float(minp))
    if maxp: sql+=\' AND p.price<=?\'; args.append(float(maxp))
    sql+=\' GROUP BY p.id\'
    sql+=({\'price_asc\':\' ORDER BY p.price ASC\',\'price_desc\':\' ORDER BY p.price DESC\',
           \'rating\':\' ORDER BY avg_rating DESC\'}).get(sort,\' ORDER BY p.created_at DESC\')
    products=conn.execute(sql,args).fetchall()
    categories=[r[0] for r in conn.execute(\'SELECT DISTINCT category FROM products\').fetchall()]
    conn.close()
    return render_template(\'customer/index.html\',products=products,categories=categories,
                           q=q,selected_cat=cat,min_price=minp,max_price=maxp,sort=sort)

@app.route(\'/product/<int:pid>\')
def product_detail(pid):
    conn=get_db()
    p=conn.execute(\'\'\'SELECT p.*,u.name as seller_name,
                       COALESCE(sp.shop_name,u.name) as shop_name,
                       COALESCE(sp.shop_slug,\\\'\\\') as shop_slug,
                       COALESCE(AVG(r.rating),0) as avg_rating,
                       COUNT(r.id) as review_count
                       FROM products p JOIN users u ON p.seller_id=u.id
                       LEFT JOIN seller_profiles sp ON u.id=sp.user_id
                       LEFT JOIN reviews r ON p.id=r.product_id
                       WHERE p.id=? GROUP BY p.id\'\'\', (pid,)).fetchone()
    if not p: conn.close(); return render_template(\'errors/404.html\'),404
    related=conn.execute(\'SELECT * FROM products WHERE category=? AND id!=? AND stock>0 LIMIT 4\',
                         (p[\'category\'],pid)).fetchall()
    reviews=conn.execute(\'\'\'SELECT r.*,u.name as reviewer_name FROM reviews r
                            JOIN users u ON r.user_id=u.id WHERE r.product_id=?
                            ORDER BY r.created_at DESC\'\'\', (pid,)).fetchall()
    user_review=None
    if session.get(\'user_id\'):
        user_review=conn.execute(\'SELECT * FROM reviews WHERE product_id=? AND user_id=?\',
                                  (pid,session[\'user_id\'])).fetchone()
    conn.close()
    return render_template(\'customer/product_detail.html\',product=p,related=related,
                           reviews=reviews,user_review=user_review)

@app.route(\'/store/<shop_slug>\')
def seller_store(shop_slug):
    conn=get_db()
    sp=conn.execute(\'SELECT sp.*,u.name as seller_name FROM seller_profiles sp JOIN users u ON sp.user_id=u.id WHERE sp.shop_slug=?\',
                    (shop_slug,)).fetchone()
    if not sp: conn.close(); return render_template(\'errors/404.html\'),404
    q=request.args.get(\'q\',\'\').strip(); cat=request.args.get(\'category\',\'\')
    sql=\'SELECT * FROM products WHERE seller_id=? AND stock>0\'
    args=[sp[\'user_id\']]
    if q:   sql+=\' AND name LIKE ?\'; args.append(f\'%{q}%\')
    if cat: sql+=\' AND category=?\'; args.append(cat)
    sql+=\' ORDER BY created_at DESC\'
    products=conn.execute(sql,args).fetchall()
    cats=[r[0] for r in conn.execute(\'SELECT DISTINCT category FROM products WHERE seller_id=?\',
                                      (sp[\'user_id\'],)).fetchall()]
    conn.close()
    return render_template(\'customer/seller_store.html\',profile=sp,products=products,
                           categories=cats,q=q,selected_cat=cat)

@app.route(\'/product/<int:pid>/review\', methods=[\'POST\'])
@login_required
def submit_review(pid):
    rating=int(request.form.get(\'rating\',5)); comment=request.form.get(\'comment\',\'\').strip()
    if not 1<=rating<=5: flash(\'Rating must be 1-5.\',\'error\'); return redirect(url_for(\'product_detail\',pid=pid))
    conn=get_db()
    existing=conn.execute(\'SELECT id FROM reviews WHERE product_id=? AND user_id=?\',
                           (pid,session[\'user_id\'])).fetchone()
    if existing:
        conn.execute(\'UPDATE reviews SET rating=?,comment=? WHERE id=?\',(rating,comment,existing[\'id\']))
        flash(\'Review updated!\',\'success\')
    else:
        conn.execute(\'INSERT INTO reviews (product_id,user_id,rating,comment) VALUES (?,?,?,?)\',
                     (pid,session[\'user_id\'],rating,comment))
        flash(\'Review submitted!\',\'success\')
    conn.commit(); conn.close()
    return redirect(url_for(\'product_detail\',pid=pid))

@app.route(\'/product/<int:pid>/review/delete\', methods=[\'POST\'])
@login_required
def delete_review(pid):
    conn=get_db()
    conn.execute(\'DELETE FROM reviews WHERE product_id=? AND user_id=?\',(pid,session[\'user_id\']))
    conn.commit(); conn.close()
    flash(\'Review deleted.\',\'info\')
    return redirect(url_for(\'product_deta'
il\',pid=pid))
''