"""
ai_engine/exporter.py — Multi-Framework Export Engine
Converts generated static HTML/CSS/JS into React, Next.js, or clean static HTML.
"""
import re
from utils.logger import get_logger

logger = get_logger("ai_engine.exporter")

SUPPORTED_FRAMEWORKS = ["static", "react", "nextjs"]


def export_to_react(project_files: dict, site_name: str) -> dict:
    """
    Convert a static HTML project to a React app.
    Returns dict of new files for the React project.
    """
    html = project_files.get("index.html", "")
    css  = project_files.get("style.css", "")
    js   = project_files.get("script.js", "")

    safe_name = re.sub(r"[^a-zA-Z0-9]", "", site_name) or "MyApp"

    files = {}

    # package.json
    files["package.json"] = f'''{{
  "name": "{safe_name.lower()}",
  "version": "0.1.0",
  "private": true,
  "dependencies": {{
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1"
  }},
  "scripts": {{
    "start": "react-scripts start",
    "build": "react-scripts build"
  }},
  "browserslist": {{
    "production": [">0.2%", "not dead"],
    "development": ["last 1 chrome version"]
  }}
}}'''

    # src/App.js — convert HTML body to JSX
    jsx_body = _html_to_jsx(html)
    files["src/App.js"] = f'''import React from 'react';
import './App.css';

function App() {{
  return (
    <div className="App">
{jsx_body}
    </div>
  );
}}

export default App;
'''

    # src/App.css
    files["src/App.css"] = css

    # src/index.js
    files["src/index.js"] = '''import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<React.StrictMode><App /></React.StrictMode>);
'''

    files["src/index.css"] = "* { box-sizing: border-box; margin: 0; padding: 0; }"

    # public/index.html
    files["public/index.html"] = f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>{site_name}</title>
</head>
<body>
  <noscript>You need to enable JavaScript to run this app.</noscript>
  <div id="root"></div>
</body>
</html>'''

    # README
    files["README.md"] = f'''# {site_name} — React App

Generated by WebGen AI Website Builder.

## Getting Started

```bash
npm install
npm start
```

Open [http://localhost:3000](http://localhost:3000) to view it in the browser.

## Build for Production

```bash
npm run build
```
'''

    logger.info("Exported to React: %s (%d files)", site_name, len(files))
    return files


def export_to_nextjs(project_files: dict, site_name: str) -> dict:
    """
    Convert a static HTML project to a Next.js app.
    Returns dict of new files for the Next.js project.
    """
    html = project_files.get("index.html", "")
    css  = project_files.get("style.css", "")
    safe_name = re.sub(r"[^a-zA-Z0-9]", "", site_name) or "MyApp"

    files = {}

    # package.json
    files["package.json"] = f'''{{
  "name": "{safe_name.lower()}",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  }},
  "dependencies": {{
    "next": "14.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }}
}}'''

    # pages/index.js
    jsx_body = _html_to_jsx(html)
    files["pages/index.js"] = f'''import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {{
  return (
    <>
      <Head>
        <title>{site_name}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>
      <main>
{jsx_body}
      </main>
    </>
  );
}}
'''

    # pages/_app.js
    files["pages/_app.js"] = '''import '../styles/globals.css';
export default function App({ Component, pageProps }) {
  return <Component {...pageProps} />;
}
'''

    # styles
    files["styles/globals.css"] = css
    files["styles/Home.module.css"] = ""

    # next.config.js
    files["next.config.js"] = '''/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
module.exports = nextConfig;
'''

    # README
    files["README.md"] = f'''# {site_name} — Next.js App

Generated by WebGen AI Website Builder.

## Getting Started

```bash
npm install
npm run dev
```

Open [http://localhost:3000](http://localhost:3000) to view it.

## Deploy on Vercel

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new)
'''

    logger.info("Exported to Next.js: %s (%d files)", site_name, len(files))
    return files


def _html_to_jsx(html: str) -> str:
    """Convert HTML body content to JSX-compatible string."""
    # Extract body content
    body_match = re.search(r"<body[^>]*>(.*?)</body>", html, re.DOTALL)
    body = body_match.group(1).strip() if body_match else html

    # JSX conversions
    body = re.sub(r'\bclass=', 'className=', body)
    body = re.sub(r'\bfor=', 'htmlFor=', body)
    body = re.sub(r'<(br|hr|img|input|link|meta)([^/]*)(?<!/)>', r'<\1\2/>', body)
    body = re.sub(r'<!--.*?-->', '', body, flags=re.DOTALL)

    # Indent
    lines = body.split('\n')
    return '\n'.join('      ' + line for line in lines if line.strip())
