'use strict';
// Generated by Website Builder System — NovaTech

// ── Dark mode ─────────────────────────────────────────────────────────────────
function applyDark(isDark) {
  document.documentElement.classList.toggle('dark', isDark);
  const sun  = document.getElementById('iconSun');
  const moon = document.getElementById('iconMoon');
  if (sun)  sun.classList.toggle('hidden', !isDark);
  if (moon) moon.classList.toggle('hidden', isDark);
}
function toggleDark() {
  const isDark = !document.documentElement.classList.contains('dark');
  localStorage.setItem('dark', isDark);
  applyDark(isDark);
}
applyDark(localStorage.getItem('dark') === 'true');

// ── Scroll reveal ─────────────────────────────────────────────────────────────
const revealObserver = new IntersectionObserver(entries => {
  entries.forEach(e => {
    if (e.isIntersecting) { e.target.classList.add('visible'); revealObserver.unobserve(e.target); }
  });
}, { threshold: 0.1, rootMargin: '0px 0px -40px 0px' });
document.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('.reveal,.reveal-left,.reveal-right').forEach(el => revealObserver.observe(el));
});

// ── Counter animation ─────────────────────────────────────────────────────────
function animateCounter(el) {
  const target = parseInt(el.dataset.target);
  const suffix = el.dataset.suffix || '';
  let count = 0;
  const step = Math.ceil(target / 60);
  const timer = setInterval(() => {
    count = Math.min(count + step, target);
    el.textContent = count.toLocaleString() + suffix;
    if (count >= target) clearInterval(timer);
  }, 22);
}
const counterObserver = new IntersectionObserver(entries => {
  entries.forEach(e => {
    if (e.isIntersecting) {
      e.target.querySelectorAll('[data-target]').forEach(animateCounter);
      counterObserver.unobserve(e.target);
    }
  });
}, { threshold: 0.4 });
document.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('.stats-row').forEach(el => counterObserver.observe(el));
});

// ── Scroll progress ───────────────────────────────────────────────────────────
const progressBar = document.getElementById('scrollProgress');

// ── Back to top ───────────────────────────────────────────────────────────────
const backToTop = document.getElementById('backToTop');

window.addEventListener('scroll', () => {
  if (progressBar) progressBar.style.transform = `scaleX(${scrollY / (document.documentElement.scrollHeight - innerHeight) || 0})`;
  if (backToTop) backToTop.classList.toggle('visible', scrollY > 400);
  const nav = document.getElementById('mainNav'); if (nav) nav.style.boxShadow = scrollY > 8 ? '0 4px 24px rgba(0,0,0,.12)' : 'none';
}, { passive: true });

// ── Active nav link ───────────────────────────────────────────────────────────
(function() {
  const page = location.pathname.split('/').pop() || 'index.html';
  document.querySelectorAll('.nav-link').forEach(a => {
    const href = (a.getAttribute('href') || '').split('/').pop();
    if (href === page || (page === '' && href === 'index.html')) a.classList.add('active');
  });
})();

// ── Toast ─────────────────────────────────────────────────────────────────────
window.showToast = function(msg, type = 'success') {
  const colors = { success:'bg-emerald-500', error:'bg-red-500', info:'bg-blue-500', warning:'bg-amber-500' };
  const t = document.createElement('div');
  t.className = `fixed bottom-6 right-6 z-[9999] px-5 py-3 rounded-2xl text-white text-sm font-semibold shadow-2xl toast-enter flex items-center gap-2 ${colors[type] || colors.success}`;
  t.innerHTML = `<span>${msg}</span><button onclick="this.parentElement.remove()" class="ml-2 opacity-70 hover:opacity-100 text-lg leading-none" aria-label="Close">×</button>`;
  document.body.appendChild(t);
  setTimeout(() => { t.classList.add('toast-leave'); setTimeout(() => t.remove(), 300); }, 3500);
};

// ── Contact form ──────────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  const cf = document.getElementById('contactForm');
  if (cf) {
    cf.addEventListener('submit', e => {
      e.preventDefault();
      const btn = cf.querySelector('[type=submit]');
      const orig = btn.textContent;
      btn.textContent = 'Sending…'; btn.disabled = true;
      setTimeout(() => {
        cf.reset(); btn.textContent = orig; btn.disabled = false;
        showToast("Message sent! We'll get back to you soon. ✅");
      }, 1200);
    });
  }
});

// ── Smooth anchor scroll ──────────────────────────────────────────────────────
document.addEventListener('click', e => {
  const a = e.target.closest('a[href^="#"]');
  if (!a) return;
  const target = document.querySelector(a.getAttribute('href'));
  if (target) { e.preventDefault(); target.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
});
